### ISSUE TITLE
First meeting - Jan 25

### ISSUE THREAD

**Issue by liuzhen529** [aiod01/STAT550-450-for-Seniorworkers-from-Korea#1]
1. Make sure there are four response variables: two for skills and two for information-processing proficiency. They are all continuous.

2. There are three groups of explanatory variables: 
   1. {X1}: demographic factors (ages, gender, ..)
   2. {X2}: organizational contexts
   3. {X3}: learning/education (learning activities, education level…)

3. Rough plans:
    1) Find the optimal model for each response: Y ~ {X1} + {X2} + {X3}
            - Use all variables first
            - Variable selection
            - Comparison, see which factor in {X1}, which in {X2}, and which in {X3}
    2) Find the significant model each group for each response:
            - Y ~ {X1}, select the significant factors in demographic factors.
            - Y ~ {X2}, select the significant factors in organizational factors.
            - Y ~ {X3}, select the significant factors in learning/education factors.
    3) Compare the effects among three groups.

**Comment by KellyHu** [comment]
I think your Y here should be Yi, where i=1,2,3,4 because we have four Ys. In my opinion, we should fit each x with each y respectively.

**Comment by liuzhen529** [comment]
Yes. I said for each response already.

**Comment by KellyHu** [comment]
Nice! Cuz I saw you specifying X as X1, X2, X3, but did not specify Y as Y1, Y2, Y3, Y4. Maybe we can write these down as well :)

Zhen: If you want, you could edit my post above and then we could divide our tasks. Thanks.
