### ISSUE TITLE
translate assorted variables-labels & scales.txt

### ISSUE THREAD

**Issue by Lindaaaaaa** [aiod01/STAT550-450-for-Seniorworkers-from-Korea#2]
@aiod01 
Hi,  I think this metadata file needs to be translate into English since it contains what does each level represent for categorical variable. 
Could you please help with that? Very much appreciated!

**Comment by tom-hc-park** [comment]
sure, will finish it till Sunday, tomorrow!

**Comment by tom-hc-park** [comment]
@Lindaaaaaa 
I translated the txt file. Let me know if you still confuse with some sentences.

**Comment by Lindaaaaaa** [comment]
@aiod01 Great! Thank you so much.
