### ISSUE TITLE
csv file for sav file.

### ISSUE THREAD

**Issue by tom-hc-park** [aiod01/STAT550-450-for-Seniorworkers-from-Korea#3]
@hyunokryu 
Hi hyunok,

Could you upload csv file version of  Data-NFEHRS_revised.sav?
I don't have SPSS in my computer so cannot open the file :(

Thanks!

**Comment by Lindaaaaaa** [comment]
R supports reading from sav file. 
You could just view the data in R with the following command
data<- read_sav("path to the file")
View(data)

**Comment by tom-hc-park** [comment]
Oh awesome, thanks! :)
